#!/bin/sh
# Bring Mochimo online -- from any state
# Copyright (c) 2022 by Adequate Systems, LLC.  All Rights Reserved.
# See https://mochimo.org/license.pdf   **** NO WARRANTY ****
#

###################
# Preconfiguration

trap "" 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
trap ""  24 25 26 27 28 29 30 31
trap "exit 0" term

# File security
umask 077

# Move to script directory
cd "$( cd "$( dirname "${BASH_SOURCE:-$0}" )" && pwd )"

# Set working directory to...
WDIR=${1:-d/}  # ... first argument, or d/ directory, AND
# ... fallback to d/ if first argument starts with a dash "-"
CHAR=$(printf '%s' $WDIR | cut -c1)
if test "$CHAR" = "-"; then WDIR="d/"; fi

################
# Sanity checks

echo
if test ! -f mochimo
then echo -e "Missing 'mochimo' binary: check installation\n" && exit 1
fi

########
# Start

# Create and enter working directory
mkdir -p $WDIR && cd $WDIR
#../mochimo -x345678 -e -l -t1 -d  $2 $3 $4 $5 $6 $7 $8 $9
../mochimo -x345678 -o -F -P -s1000 $1 $2 $3 $4 $5 $6 $7 $8 $9
echo && echo "Mochimo stopped..."
